#1-git (needed to do the clone)
FROM alpine/git as repo 
WORKDIR /app
RUN git clone https://github.com/nfestaclass004/maven-web-application.git
#2-maven (to do a build)
FROM maven:3.5-jdk-8-alpine as build
WORKDIR /app
COPY --from=repo /app/maven-web-application /app
RUN mvn clean package
#3-tomcat (for app deployment)
FROM tomcat:9-jre9-slim
COPY --from=build /app/target/*war /usr/local/tomcat/webapps/app.war
